export interface Location {
  id: number;
  name: string;
  chineseName: string;
  province: string;
  coords: [number, number]; // [lat, lng]
  description: string;
  bestTime: string;
  highlights: string[];
  emoji: string;
}

export const CHINA_LOCATIONS: Location[] = [
  // Beijing
  { id: 1, name: "Palace Museum (Forbidden City)", chineseName: "故宫博物院", province: "Beijing", coords: [39.916, 116.391], description: "The world's largest palace complex, home to Ming and Qing emperors for 500 years.", bestTime: "Apr–Jun, Sep–Oct", highlights: ["Hall of Supreme Harmony", "Imperial Garden", "Treasure Gallery"], emoji: "🏯" },
  { id: 2, name: "Badaling Great Wall", chineseName: "八达岭长城", province: "Beijing", coords: [40.358, 116.010], description: "The most visited and well-restored section of the Great Wall of China.", bestTime: "Apr–Jun, Sep–Nov", highlights: ["North Tower", "Cable car", "Wall museum"], emoji: "🧱" },
  { id: 3, name: "Summer Palace", chineseName: "颐和园", province: "Beijing", coords: [39.999, 116.275], description: "A vast imperial garden with Kunming Lake and Longevity Hill, the ultimate royal retreat.", bestTime: "Apr–Oct", highlights: ["Long Corridor", "Marble Boat", "Suzhou Street"], emoji: "🌿" },
  { id: 4, name: "Temple of Heaven", chineseName: "天坛公园", province: "Beijing", coords: [39.883, 116.411], description: "A masterpiece of Ming architecture where emperors prayed for good harvests.", bestTime: "Year-round", highlights: ["Hall of Prayer", "Echo Wall", "Imperial Vault"], emoji: "⛪" },
  { id: 5, name: "Ming Tombs", chineseName: "明十三陵", province: "Beijing", coords: [40.252, 116.221], description: "Thirteen imperial mausoleums of the Ming dynasty nestled in a valley north of Beijing.", bestTime: "Apr–Oct", highlights: ["Sacred Way", "Changling Tomb", "Dingling Underground Palace"], emoji: "⚰️" },
  // Tianjin
  { id: 6, name: "Panshan Scenic Area", chineseName: "盘山风景名胜区", province: "Tianjin", coords: [40.112, 117.412], description: "A sacred mountain renowned as the 'First Mountain East of Beijing' with ancient temples.", bestTime: "Apr–Oct", highlights: ["Tianmen Peak", "Shengshui Temple", "Thousand Tread Steps"], emoji: "⛰️" },
  // Hebei
  { id: 7, name: "Chengde Mountain Resort", chineseName: "承德避暑山庄", province: "Hebei", coords: [40.996, 117.944], description: "The largest imperial garden in China, a Qing dynasty summer retreat surrounded by Eight Outer Temples.", bestTime: "Jun–Sep", highlights: ["Bishu Shanzhuang", "Putuo Zongcheng Temple", "Puning Temple"], emoji: "🏔️" },
  { id: 8, name: "Wild Valley (Yesanpo)", chineseName: "野三坡", province: "Hebei", coords: [39.558, 115.383], description: "A dramatic canyon landscape with gorges, rivers and ancient cliff dwellings.", bestTime: "Apr–Oct", highlights: ["Baicat Gorge", "Baocaodi", "Longmen Gorge"], emoji: "🏞️" },
  // Shanxi
  { id: 9, name: "Wutai Mountain", chineseName: "五台山", province: "Shanxi", coords: [38.959, 113.569], description: "A UNESCO World Heritage sacred Buddhist mountain with over 50 ancient monasteries.", bestTime: "May–Oct", highlights: ["Foguang Temple", "Nanchan Temple", "Xiantong Monastery"], emoji: "🛕" },
  { id: 10, name: "Pingyao Ancient City", chineseName: "平遥古城", province: "Shanxi", coords: [37.199, 112.175], description: "A UNESCO-listed Ming dynasty walled city, the best preserved ancient town in China.", bestTime: "Apr–Oct", highlights: ["City Wall", "Rishengchang Exchange Shop", "City God Temple"], emoji: "🏘️" },
  { id: 11, name: "Yungang Grottoes", chineseName: "云冈石窟", province: "Shanxi", coords: [40.110, 113.130], description: "UNESCO-listed Buddhist rock carvings from the 5th–6th century with over 51,000 statues.", bestTime: "Apr–Oct", highlights: ["Cave 5 & 6", "Giant Buddha", "Tan Yao Five Caves"], emoji: "🗿" },
  // Inner Mongolia
  { id: 12, name: "Genghis Khan Mausoleum", chineseName: "成吉思汗陵旅游区", province: "Inner Mongolia", coords: [39.680, 110.080], description: "The ceremonial mausoleum of the great Mongol conqueror, a pilgrimage site for Mongolians.", bestTime: "May–Sep", highlights: ["Main Hall", "Ordos Palace", "Grassland scenery"], emoji: "🏇" },
  // Liaoning
  { id: 13, name: "Shenyang Palace Museum", chineseName: "沈阳故宫", province: "Liaoning", coords: [41.794, 123.438], description: "The imperial palace built by the Manchu Qing founders before moving to Beijing.", bestTime: "Apr–Oct", highlights: ["Dazheng Hall", "Ten Kings Pavilions", "Imperial Treasury"], emoji: "🏯" },
  { id: 14, name: "Benxi Water Cave", chineseName: "本溪水洞", province: "Liaoning", coords: [41.285, 124.145], description: "One of the world's longest underground rivers with stunning limestone formations.", bestTime: "Year-round", highlights: ["Underground river boat ride", "Crystal formations", "Dragon Palace"], emoji: "🕳️" },
  // Jilin
  { id: 15, name: "Changbai Mountain", chineseName: "长白山", province: "Jilin", coords: [42.010, 128.081], description: "An active volcano with the stunning Heaven Lake crater lake on the China-Korea border.", bestTime: "Jun–Sep", highlights: ["Heaven Lake", "Tianchi Waterfall", "Hot springs"], emoji: "🌋" },
  // Heilongjiang
  { id: 16, name: "Jingpo Lake", chineseName: "镜泊湖", province: "Heilongjiang", coords: [44.000, 129.000], description: "A volcanic barrier lake with lava cave forests, waterfalls and dramatic crater scenery.", bestTime: "Jun–Sep", highlights: ["Diaoshuilou Waterfall", "Underground Forest", "Lava Caves"], emoji: "🌊" },
  // Shanghai
  { id: 17, name: "Yu Garden", chineseName: "豫园", province: "Shanghai", coords: [31.227, 121.492], description: "A classical Ming dynasty private garden with exquisite rockeries, pavilions and ponds.", bestTime: "Mar–May, Sep–Nov", highlights: ["Grand Rockery", "Hall of Jade Magnificence", "Bazaar"], emoji: "🌺" },
  // Jiangsu
  { id: 18, name: "Zhongshan Scenic Area", chineseName: "钟山风景名胜区", province: "Jiangsu", coords: [32.064, 118.865], description: "A wooded mountain park in Nanjing housing Sun Yat-sen's Mausoleum and Ming Xiaoling.", bestTime: "Apr–Jun, Sep–Nov", highlights: ["Sun Yat-sen Mausoleum", "Ming Xiaoling", "Linggu Temple"], emoji: "🌳" },
  { id: 19, name: "Suzhou Classical Gardens", chineseName: "苏州古典园林", province: "Jiangsu", coords: [31.324, 120.631], description: "UNESCO-listed classical gardens showcasing the pinnacle of Chinese garden design.", bestTime: "Mar–May, Sep–Nov", highlights: ["Humble Administrator's Garden", "Master of Nets", "Lingering Garden"], emoji: "🎋" },
  { id: 20, name: "Taihu Lake", chineseName: "太湖风景名胜区", province: "Jiangsu", coords: [31.200, 120.200], description: "China's third largest freshwater lake, dotted with islands and famous for its Taihu stones.", bestTime: "Mar–Nov", highlights: ["Turtle Head Isle", "Lingshan Grand Buddha", "Sanshan Island"], emoji: "🏝️" },
  // Zhejiang
  { id: 21, name: "West Lake", chineseName: "西湖", province: "Zhejiang", coords: [30.253, 120.155], description: "A UNESCO World Heritage lake in Hangzhou surrounded by pavilions, causeways and classical gardens.", bestTime: "Mar–Jun, Sep–Nov", highlights: ["Broken Bridge", "Leifeng Pagoda", "Su Causeway"], emoji: "🌸" },
  { id: 22, name: "Putuo Mountain", chineseName: "普陀山", province: "Zhejiang", coords: [29.994, 122.379], description: "A sacred Buddhist island considered the bodhimanda of Guanyin, goddess of mercy.", bestTime: "Apr–Nov", highlights: ["Nanhai Guanyin statue", "Puji Temple", "Chaoyin Cave"], emoji: "🛕" },
  { id: 23, name: "Yandang Mountain", chineseName: "雁荡山", province: "Zhejiang", coords: [28.367, 121.050], description: "Dramatic peaks, waterfalls and grottoes in eastern Zhejiang, a top scenic mountain.", bestTime: "Apr–Oct", highlights: ["Lingfeng Peak", "Dalongqiu Waterfall", "Lingyan Temple"], emoji: "⛰️" },
  { id: 24, name: "Qiandao Lake", chineseName: "千岛湖", province: "Zhejiang", coords: [29.605, 119.033], description: "A vast reservoir with 1,078 forested islands created by a 1959 dam, crystal-clear water.", bestTime: "Apr–Oct", highlights: ["Meishan Island", "Longshan Island", "Fish Head Restaurant"], emoji: "🏝️" },
  // Anhui
  { id: 25, name: "Huangshan", chineseName: "黄山", province: "Anhui", coords: [30.133, 118.166], description: "The iconic Yellow Mountain with ancient pines, granite peaks and seas of clouds.", bestTime: "Mar–Nov", highlights: ["Flying Over Rock", "West Sea Grand Canyon", "Bright Summit"], emoji: "🌫️" },
  { id: 26, name: "Jiuhua Mountain", chineseName: "九华山", province: "Anhui", coords: [30.488, 117.816], description: "One of China's four sacred Buddhist mountains, dedicated to Ksitigarbha Bodhisattva.", bestTime: "Apr–Oct", highlights: ["Roushen Hall", "Tiantai Peak", "Huacheng Temple"], emoji: "🛕" },
  // Fujian
  { id: 27, name: "Wuyi Mountain", chineseName: "武夷山", province: "Fujian", coords: [27.726, 117.979], description: "A UNESCO dual World Heritage site with dramatic Nine-Bend River scenery and ancient tea culture.", bestTime: "Mar–Nov", highlights: ["Nine-Bend Stream raft", "Tianyou Peak", "Dahongpao tea", "Han Tomb"], emoji: "🍵" },
  { id: 28, name: "Gulangyu Island", chineseName: "鼓浪屿", province: "Fujian", coords: [24.447, 118.065], description: "A UNESCO-listed pedestrian island off Xiamen with colonial architecture and piano culture.", bestTime: "Year-round", highlights: ["Sunlight Rock", "Piano Museum", "Shuzhuang Garden"], emoji: "🎹" },
  { id: 29, name: "Taining Scenic Area", chineseName: "泰宁", province: "Fujian", coords: [26.901, 117.169], description: "A UNESCO Geopark with red sandstone danxia landforms, lakes and ancient Confucian academy.", bestTime: "Apr–Oct", highlights: ["Jinhu Lake", "Danxia peaks", "Shangyuan", "Qingliyan"], emoji: "🔴" },
  // Jiangxi
  { id: 30, name: "Lushan Mountain", chineseName: "庐山", province: "Jiangxi", coords: [29.578, 115.990], description: "A UNESCO World Heritage mountain above Poyang Lake, famous for mist, waterfalls and villas.", bestTime: "Apr–Oct", highlights: ["Hanpokou", "Meilu Villa", "Three-step Waterfall"], emoji: "🌁" },
  { id: 31, name: "Jingdezhen Ceramic Culture", chineseName: "景德镇陶瓷文化", province: "Jiangxi", coords: [29.286, 117.215], description: "The millennium-old 'porcelain capital' of China with ancient kilns and ceramic craft.", bestTime: "Apr–Oct", highlights: ["Ancient Kiln Folk Scenic Area", "Imperial Kiln", "Ceramic History Museum"], emoji: "🏺" },
  { id: 32, name: "Sanqing Mountain", chineseName: "三清山", province: "Jiangxi", coords: [28.907, 118.063], description: "A UNESCO Geopark with bizarre granite pillars resembling Taoist immortals in a sea of clouds.", bestTime: "Mar–Nov", highlights: ["Western Sea Skywalk", "Python Emerging from Mountain", "Goddess Peak"], emoji: "☁️" },
  { id: 33, name: "Longhu Mountain", chineseName: "龙虎山", province: "Jiangxi", coords: [28.016, 116.932], description: "The birthplace of Taoism, a UNESCO Geopark with clifftop hanging coffins and danxia scenery.", bestTime: "Apr–Oct", highlights: ["Hanging Coffins", "Zhengyi Ancient Town", "Luxi River raft"], emoji: "⚰️" },
  // Shandong
  { id: 34, name: "Mount Tai", chineseName: "泰山", province: "Shandong", coords: [36.268, 117.103], description: "The most revered of China's Five Sacred Mountains, a UNESCO World Heritage site.", bestTime: "Apr–Oct", highlights: ["Jade Emperor Peak", "South Gate to Heaven", "Sunrise viewing"], emoji: "🌄" },
  { id: 35, name: "Qufu Confucius Sites", chineseName: "曲阜孔庙孔林孔府", province: "Shandong", coords: [35.597, 116.990], description: "The UNESCO-listed hometown of Confucius with temple, family mansion and cemetery.", bestTime: "Apr–Oct", highlights: ["Confucius Temple", "Confucius Forest", "Kong Family Mansion"], emoji: "📚" },
  { id: 36, name: "Mount Yi Scenic Area", chineseName: "沂蒙山", province: "Shandong", coords: [35.500, 118.100], description: "A revolutionary-era mountain resort with scenic peaks, valleys and ancient villages.", bestTime: "Apr–Oct", highlights: ["Mengshan Peak", "Cloud and Sea Temple", "Waterfall Valley"], emoji: "🏔️" },
  // Henan
  { id: 37, name: "Longmen Grottoes", chineseName: "龙门石窟", province: "Henan", coords: [34.551, 112.473], description: "A UNESCO World Heritage site with 110,000 Buddhist stone carvings along a riverside cliff.", bestTime: "Apr–Oct", highlights: ["Fengxian Temple Giant Buddha", "Guyang Cave", "East Hill Grottoes"], emoji: "🗿" },
  { id: 38, name: "Shaolin Temple", chineseName: "少林寺", province: "Henan", coords: [34.508, 112.939], description: "The birthplace of Chan Buddhism and Chinese martial arts, on the sacred Song Mountain.", bestTime: "Mar–Nov", highlights: ["Martial arts performance", "Pagoda Forest", "Bodhidharma Cave"], emoji: "🥋" },
  { id: 39, name: "Yuntai Mountain", chineseName: "云台山", province: "Henan", coords: [35.429, 113.293], description: "A dramatic UNESCO Geopark with deep red-walled canyons, waterfalls and crystal pools.", bestTime: "Apr–Oct", highlights: ["Red Stone Gorge", "Tanpu Gorge", "Quanpu Waterfall"], emoji: "🏞️" },
  { id: 40, name: "Qingming Riverside Landscape Garden", chineseName: "清明上河园", province: "Henan", coords: [34.789, 114.306], description: "A Song dynasty theme park in Kaifeng recreating the famous Qingming Festival scroll painting.", bestTime: "Year-round", highlights: ["Rainbow Bridge", "Song Dynasty performances", "Grand Theatre"], emoji: "🎭" },
  // Hubei
  { id: 41, name: "Wudang Mountain", chineseName: "武当山", province: "Hubei", coords: [32.401, 111.005], description: "A UNESCO World Heritage Taoist mountain with ancient temples, martial arts and stunning scenery.", bestTime: "Apr–Oct", highlights: ["Golden Hall", "Nanyan Palace", "Wudang kung fu"], emoji: "🥋" },
  { id: 42, name: "Three Gorges", chineseName: "三峡", province: "Hubei", coords: [30.700, 110.700], description: "The world's largest hydroelectric project and dramatic river gorges through the mountains.", bestTime: "Apr–Jun, Sep–Oct", highlights: ["Qutang Gorge", "Wu Gorge", "Xiling Gorge"], emoji: "🌊" },
  // Hunan
  { id: 43, name: "Zhangjiajie National Forest Park", chineseName: "张家界国家森林公园", province: "Hunan", coords: [29.325, 110.435], description: "The otherworldly sandstone pillar landscape that inspired Avatar's Hallelujah Mountains.", bestTime: "Apr–Nov", highlights: ["Tianzi Mountain", "Yuanjiajie", "Golden Whip Stream"], emoji: "🏔️" },
  { id: 44, name: "Tianmen Mountain", chineseName: "天门山", province: "Hunan", coords: [29.055, 110.473], description: "A dramatic peak with the world's longest cable car and the iconic Tianmen Cave arch.", bestTime: "Apr–Oct", highlights: ["Tianmen Cave", "Glass Skywalk", "99 bends road"], emoji: "🕳️" },
  { id: 45, name: "Dongting Lake", chineseName: "洞庭湖", province: "Hunan", coords: [29.300, 112.900], description: "China's second largest freshwater lake, home to migratory birds and the Dragon Boat Festival origin.", bestTime: "Apr–Oct", highlights: ["Junshan Island", "Yueyang Tower", "Bird watching"], emoji: "🦢" },
  { id: 46, name: "Shaoshan", chineseName: "韶山", province: "Hunan", coords: [27.900, 112.533], description: "The birthplace of Mao Zedong, a major patriotic tourism destination.", bestTime: "Year-round", highlights: ["Mao's Birthplace", "Mao Zedong Square", "Memorial Museum"], emoji: "⭐" },
  { id: 47, name: "Fenghuang Ancient Town", chineseName: "凤凰古城", province: "Hunan", coords: [27.946, 109.601], description: "A well-preserved Ming and Qing dynasty Miao ethnic minority town on the Tuo River.", bestTime: "Apr–Oct", highlights: ["Stilted houses on water", "Hong Bridge", "City walls"], emoji: "🏘️" },
  // Guangdong
  { id: 48, name: "Danxia Mountain", chineseName: "丹霞山", province: "Guangdong", coords: [25.019, 113.736], description: "A UNESCO World Heritage Geopark with vivid red sandstone formations and Buddhist temples.", bestTime: "Mar–Nov", highlights: ["Yangyuan Stone", "Piantai Cliff", "Baiyun Cave"], emoji: "🔴" },
  { id: 49, name: "Xiqiao Mountain", chineseName: "西樵山", province: "Guangdong", coords: [22.981, 113.005], description: "A dormant volcanic mountain in the Pearl River Delta with waterfalls, caves and temples.", bestTime: "Mar–Nov", highlights: ["South Sea Guanyin", "Tianlv Lake", "Yumeng Cave"], emoji: "🌋" },
  // Guangxi
  { id: 50, name: "Guilin Lijiang River", chineseName: "桂林漓江", province: "Guangxi", coords: [25.274, 110.290], description: "The iconic karst mountain and river landscape featured on the 20 yuan banknote.", bestTime: "Apr–Oct", highlights: ["Li River cruise", "Yangshuo", "Reed Flute Cave", "Elephant Trunk Hill"], emoji: "⛰️" },
  { id: 51, name: "Detian Waterfall", chineseName: "德天跨国大瀑布", province: "Guangxi", coords: [22.826, 106.697], description: "Asia's largest transnational waterfall on the China-Vietnam border, an awe-inspiring cascade.", bestTime: "May–Oct", highlights: ["Main falls", "Bamboo raft tour", "Vietnam border bridge"], emoji: "💧" },
  { id: 52, name: "Beihai Silver Beach", chineseName: "北海银滩", province: "Guangxi", coords: [21.474, 109.168], description: "A 24km white sand beach on the Beibu Gulf coast, one of China's finest.", bestTime: "Apr–Oct", highlights: ["Silver Beach", "Underwater World", "Weizhou Island nearby"], emoji: "🏖️" },
  // Hainan
  { id: 53, name: "Sanya Tianyahaijiao", chineseName: "天涯海角", province: "Hainan", coords: [18.239, 109.286], description: "A scenic beach at the southernmost tip of Hainan with legendary 'End of the World' rocks.", bestTime: "Oct–Apr", highlights: ["End of World Rock", "Cape of No Return", "Sea Stones"], emoji: "🌊" },
  { id: 54, name: "Nanshan Cultural Tourism Area", chineseName: "南山文化旅游区", province: "Hainan", coords: [18.278, 109.198], description: "A grand Buddhist cultural complex featuring a 108m Guanyin statue standing in the sea.", bestTime: "Year-round", highlights: ["108m Guanyin", "Nanshan Temple", "Sea of Fortune"], emoji: "🛕" },
  // Chongqing
  { id: 55, name: "Dazu Rock Carvings", chineseName: "大足石刻", province: "Chongqing", coords: [29.700, 105.714], description: "A UNESCO World Heritage site with outstanding Tang–Song dynasty Buddhist carvings on cliffs.", bestTime: "Mar–Nov", highlights: ["Beishan Rock Carvings", "Baodingshan", "Nanshan"], emoji: "🗿" },
  { id: 56, name: "Wulong Karst", chineseName: "武隆喀斯特", province: "Chongqing", coords: [29.323, 107.762], description: "A UNESCO World Heritage karst landscape with giant sinkholes, natural bridges and caves.", bestTime: "Apr–Oct", highlights: ["Three Natural Bridges", "Fairy Mountain", "Furong Cave"], emoji: "🌉" },
  // Sichuan
  { id: 57, name: "Jiuzhaigou Valley", chineseName: "九寨沟", province: "Sichuan", coords: [33.260, 103.918], description: "A UNESCO World Heritage valley with multi-colored lakes, waterfalls and snow peaks.", bestTime: "Sep–Nov", highlights: ["Five-Flower Lake", "Nuorilang Falls", "Pearl Shoal"], emoji: "🏞️" },
  { id: 58, name: "Huanglong Scenic Area", chineseName: "黄龙风景名胜区", province: "Sichuan", coords: [32.750, 103.817], description: "A UNESCO site with travertine pools, multi-colored ponds and ancient temples in snow mountains.", bestTime: "Jun–Oct", highlights: ["Five-Colored Pool", "Zhaga Waterfall", "Huanglong Temple"], emoji: "💛" },
  { id: 59, name: "Emei Mountain", chineseName: "峨眉山", province: "Sichuan", coords: [29.601, 103.333], description: "A UNESCO World Heritage sacred Buddhist mountain, one of China's Four Sacred Buddhist Mountains.", bestTime: "Apr–Oct", highlights: ["Golden Summit", "Wannian Monastery", "Baoguo Temple"], emoji: "🛕" },
  { id: 60, name: "Leshan Giant Buddha", chineseName: "乐山大佛", province: "Sichuan", coords: [29.543, 103.773], description: "The world's largest stone Buddha statue, a UNESCO site carved in the Tang dynasty cliff face.", bestTime: "Mar–Nov", highlights: ["71m Giant Buddha", "Boat view", "Lingshan Temple"], emoji: "🗿" },
  { id: 61, name: "Qingcheng Mountain and Dujiangyan", chineseName: "青城山—都江堰", province: "Sichuan", coords: [30.946, 103.611], description: "A UNESCO dual heritage site combining a sacred Taoist mountain with an ancient irrigation wonder.", bestTime: "Apr–Oct", highlights: ["Qingcheng Mountain", "Dujiangyan Weir", "Erwang Temple"], emoji: "💧" },
  { id: 62, name: "Siguniang Mountain", chineseName: "四姑娘山", province: "Sichuan", coords: [31.000, 102.900], description: "Four majestic peaks — the 'Alps of the Orient' — towering over 6,000 metres.", bestTime: "May–Oct", highlights: ["Changping Valley", "Shuangqiao Valley", "Haizi Valley"], emoji: "🏔️" },
  // Guizhou
  { id: 63, name: "Huangguoshu Waterfall", chineseName: "黄果树瀑布", province: "Guizhou", coords: [25.978, 105.669], description: "Asia's largest waterfall, 77m tall and 101m wide, with curtain-viewing caves behind it.", bestTime: "Jun–Oct", highlights: ["Main Waterfall", "Water Curtain Cave", "Rhinoceros Pool"], emoji: "💧" },
  { id: 64, name: "Zhijin Cave", chineseName: "织金洞", province: "Guizhou", coords: [26.637, 105.844], description: "One of China's largest and most magnificent caves with otherworldly stalagmite forests.", bestTime: "Year-round", highlights: ["Silver Rainforest", "Oriental Empire Hall", "Gianttalite"], emoji: "🕳️" },
  { id: 65, name: "Chishui Scenic Area", chineseName: "赤水", province: "Guizhou", coords: [28.572, 105.701], description: "A UNESCO Geopark with red canyon landscapes, waterfalls, bamboo forests and Jurassic tree ferns.", bestTime: "Mar–Oct", highlights: ["Sidonggou Waterfall", "Bamboo Sea", "Tianxingqiao Waterfall"], emoji: "🌿" },
  // Yunnan
  { id: 66, name: "Stone Forest", chineseName: "石林", province: "Yunnan", coords: [24.783, 103.269], description: "A UNESCO World Heritage karst 'stone forest' of grey limestone pillars rising from the earth.", bestTime: "Mar–Nov", highlights: ["Sword Peak Pool", "Naigu Stone Forest", "Sani minority culture"], emoji: "🪨" },
  { id: 67, name: "Three Parallel Rivers", chineseName: "三江并流", province: "Yunnan", coords: [27.500, 98.800], description: "A UNESCO World Heritage site where the Yangtze, Mekong and Salween rivers flow in parallel through gorges.", bestTime: "May–Oct", highlights: ["Tiger Leaping Gorge", "Meili Snow Mountain", "Nujiang Gorge"], emoji: "🏔️" },
  { id: 68, name: "Lijiang Ancient Town", chineseName: "丽江古城", province: "Yunnan", coords: [26.872, 100.235], description: "A UNESCO World Heritage Naxi minority old town with cobblestone streets and glacier backdrop.", bestTime: "Mar–Oct", highlights: ["Sifang Square", "Black Dragon Pool", "Dongba culture"], emoji: "🏘️" },
  { id: 69, name: "Yulong Snow Mountain", chineseName: "玉龙雪山", province: "Yunnan", coords: [27.101, 100.194], description: "The southernmost glacier mountain in the northern hemisphere, sacred to the Naxi people.", bestTime: "Mar–May, Sep–Nov", highlights: ["Glacier Park", "Blue Moon Valley", "Impression Lijiang show"], emoji: "🏔️" },
  { id: 70, name: "Pudacuo National Park", chineseName: "普达措国家公园", province: "Yunnan", coords: [27.900, 99.800], description: "A vast alpine plateau park in Shangri-La with glacial lakes, meadows and primeval forests.", bestTime: "May–Oct", highlights: ["Shudu Lake", "Bita Sea", "Flower meadows"], emoji: "🌼" },
  { id: 71, name: "Dali Ancient City", chineseName: "大理古城", province: "Yunnan", coords: [25.606, 100.268], description: "A Bai ethnic minority ancient walled city by Erhai Lake beneath the Cangshan mountains.", bestTime: "Mar–Oct", highlights: ["Three Pagodas", "Erhai Lake", "Cangshan hiking"], emoji: "🏛️" },
  { id: 72, name: "Xishuangbanna", chineseName: "西双版纳", province: "Yunnan", coords: [21.900, 100.797], description: "A tropical rainforest border region with Dai ethnic minority culture and rare wildlife.", bestTime: "Nov–Apr", highlights: ["Wild Elephant Valley", "Manting Park", "Dai minority village"], emoji: "🐘" },
  // Tibet
  { id: 73, name: "Potala Palace", chineseName: "布达拉宫", province: "Tibet", coords: [29.657, 91.117], description: "The iconic white-and-red winter palace of the Dalai Lamas, dominating the Lhasa skyline.", bestTime: "May–Oct", highlights: ["White Palace", "Red Palace", "Sacred chapels", "Panoramic views"], emoji: "🏯" },
  { id: 74, name: "Jokhang Temple", chineseName: "大昭寺", province: "Tibet", coords: [29.653, 91.136], description: "The most sacred Buddhist temple in Tibet, built in 647 AD at the heart of old Lhasa.", bestTime: "May–Oct", highlights: ["Golden roof", "Barkhor Street", "Jowo Shakyamuni"], emoji: "🛕" },
  { id: 75, name: "Norbulingka", chineseName: "罗布林卡", province: "Tibet", coords: [29.648, 91.094], description: "The summer palace of the Dalai Lamas, a beautiful park with Tibetan palaces and gardens.", bestTime: "May–Oct", highlights: ["Kelsang Podrang", "Chensel Podrang", "Summer festival"], emoji: "🌸" },
  { id: 76, name: "Yamdrok Lake", chineseName: "羊卓雍措", province: "Tibet", coords: [28.966, 90.683], description: "One of Tibet's three holy lakes, a turquoise gem at 4,441m altitude surrounded by snow peaks.", bestTime: "May–Oct", highlights: ["Turquoise waters", "Karola Glacier", "Panorama road"], emoji: "💧" },
  { id: 77, name: "Namtso Lake", chineseName: "纳木错", province: "Tibet", coords: [30.700, 90.500], description: "The 'Heavenly Lake' — the world's highest saltwater lake at 4,718m, a pilgrimage destination.", bestTime: "Jun–Sep", highlights: ["Tashi Peninsula", "Sunrise reflections", "Pilgrimage kora"], emoji: "🌅" },
  // Shaanxi
  { id: 78, name: "Terra Cotta Warriors", chineseName: "秦始皇帝陵及兵马俑", province: "Shaanxi", coords: [34.385, 109.279], description: "A UNESCO World Heritage archaeological wonder — thousands of life-size soldiers guarding the First Emperor.", bestTime: "Year-round", highlights: ["Pit 1 (6,000 warriors)", "Bronze chariots", "Emperor Qin's Mausoleum"], emoji: "⚔️" },
  { id: 79, name: "Huashan Mountain", chineseName: "华山", province: "Shaanxi", coords: [34.487, 110.084], description: "One of China's Five Sacred Mountains, famous for its precipitous cliff-side hiking trails.", bestTime: "Apr–Oct", highlights: ["Plank Walk in the Sky", "South Peak", "Sunrise"], emoji: "🧗" },
  { id: 80, name: "Hukou Waterfall", chineseName: "壶口瀑布", province: "Shaanxi", coords: [36.105, 110.443], description: "China's second-largest waterfall where the Yellow River narrows through a bottleneck gorge.", bestTime: "Apr–May, Sep–Oct", highlights: ["Main falls", "Rainbow mist", "Ice formations in winter"], emoji: "💧" },
  // Gansu
  { id: 81, name: "Mogao Caves", chineseName: "莫高窟", province: "Gansu", coords: [40.035, 94.810], description: "A UNESCO World Heritage site with 492 caves of Buddhist murals spanning 1,000 years of art.", bestTime: "Apr–Oct", highlights: ["Cave 17 Library Cave", "Cave 96 Giant Buddha", "Digital Exhibition Center"], emoji: "🎨" },
  { id: 82, name: "Crescent Moon Spring", chineseName: "鸣沙山月牙泉", province: "Gansu", coords: [40.073, 94.666], description: "A crescent-shaped oasis miraculously surviving for centuries amid singing sand dunes.", bestTime: "Apr–Oct", highlights: ["Crescent Lake", "Singing Sand Dunes", "Camel rides"], emoji: "🌙" },
  { id: 83, name: "Maiji Mountain Grottoes", chineseName: "麦积山石窟", province: "Gansu", coords: [34.374, 105.871], description: "A haystack-shaped mountain with 7,200 Buddhist sculptures carved into sheer cliff faces.", bestTime: "Apr–Oct", highlights: ["Nirvana Cave", "San Buddhist Caves", "Cliff pathways"], emoji: "🗿" },
  // Qinghai
  { id: 84, name: "Qinghai Lake", chineseName: "青海湖", province: "Qinghai", coords: [36.900, 100.166], description: "China's largest inland lake at 3,196m altitude, famed for its blue expanse and Tibetan culture.", bestTime: "Jun–Sep", highlights: ["Bird Island", "Sand Island", "Cycling festival"], emoji: "🔵" },
  { id: 85, name: "Kanbula National Park", chineseName: "坎布拉国家地质公园", province: "Qinghai", coords: [35.913, 102.108], description: "Dramatic red danxia cliffs rising above the Li River, one of the most striking landscapes in Qinghai.", bestTime: "May–Oct", highlights: ["Danxia peaks", "Li River boat tour", "Tibetan culture"], emoji: "🔴" },
  // Ningxia
  { id: 86, name: "Western Xia Mausoleums", chineseName: "西夏王陵", province: "Ningxia", coords: [38.517, 106.064], description: "The pyramid-like imperial tombs of the Tangut Western Xia kingdom, the 'Oriental Pyramids.'", bestTime: "Apr–Oct", highlights: ["Imperial tomb pyramids", "Museum", "Desert scenery"], emoji: "🏺" },
  // Xinjiang
  { id: 87, name: "Tianshan Tianchi", chineseName: "天山天池", province: "Xinjiang", coords: [43.881, 88.112], description: "A stunning glacial lake 1,910m high in the Tianshan Mountains, home to a Kazakh legend.", bestTime: "May–Sep", highlights: ["Tianchi Lake", "Bogda Peak views", "Yurt camp"], emoji: "🏔️" },
  { id: 88, name: "Kanas Lake", chineseName: "喀纳斯湖", province: "Xinjiang", coords: [48.700, 87.000], description: "A remote fairy-tale lake in the Altai Mountains near Russia, famous for its 'lake monster' legend.", bestTime: "Jun–Oct", highlights: ["Kanas Lake", "Autumn foliage", "Tuva villages"], emoji: "🌊" },
  { id: 89, name: "Bayanbulak Prairie", chineseName: "巴音布鲁克", province: "Xinjiang", coords: [42.900, 83.700], description: "A vast Alpine steppe at 2,500m with the stunning Nine-Bend River and whooper swan sanctuary.", bestTime: "Jun–Sep", highlights: ["Nine-Bend River sunset", "Swan Lake", "Alpine flowers"], emoji: "🦢" },
  // More from various provinces
  { id: 90, name: "Jiuzhaigou Scenic & Historic Area", chineseName: "九寨沟景区", province: "Sichuan", coords: [33.120, 103.800], description: "Extension scenic area surrounding the UNESCO Jiuzhaigou Valley.", bestTime: "Sep–Nov", highlights: ["Seasonal colours", "Rize Valley", "Zechawa Valley"], emoji: "🍂" },
  { id: 91, name: "Zhangye Danxia Landform", chineseName: "张掖丹霞", province: "Gansu", coords: [38.933, 100.850], description: "Extraordinary rainbow-coloured layered mineral rock formations, among the most vivid on earth.", bestTime: "Jul–Sep (golden hour)", highlights: ["Seven Colour Mountains", "Viewing platforms", "Sunrise/Sunset"], emoji: "🌈" },
  { id: 92, name: "Zhoushuizi Airport Scenic Zone", chineseName: "大连金石滩", province: "Liaoning", coords: [39.040, 122.040], description: "Jinshitan Golden Pebble Beach National Resort — ancient marine karst and golden sand.", bestTime: "Jun–Sep", highlights: ["Karst formations", "Beach", "Amusement park"], emoji: "🪨" },
  { id: 93, name: "Shennongjia", chineseName: "神农架", province: "Hubei", coords: [31.725, 110.176], description: "A UNESCO dual World Heritage primeval forest, home to the elusive 'Wild Man' and rare wildlife.", bestTime: "May–Oct", highlights: ["Shennong Peak", "Alpine meadow", "Golden monkey"], emoji: "🦍" },
  { id: 94, name: "Wulingyuan Scenic Area", chineseName: "武陵源风景名胜区", province: "Hunan", coords: [29.347, 110.551], description: "A UNESCO World Heritage area encompassing Zhangjiajie's most dramatic sandstone pillar scenery.", bestTime: "Apr–Nov", highlights: ["Avatar Hallelujah Mountain", "Glass Bridge", "Tianmen Mountain"], emoji: "🏔️" },
  { id: 95, name: "Hengshan Mountain", chineseName: "南岳衡山", province: "Hunan", coords: [27.251, 112.669], description: "The Southern Sacred Mountain of China, covered in temples, incense and misty forests.", bestTime: "Apr–Oct", highlights: ["Zhurong Peak", "Nanyue Temple", "Zhusheng Temple"], emoji: "🛕" },
  { id: 96, name: "Tianmen Mountain Scenic Area", chineseName: "天门山景区", province: "Hunan", coords: [29.042, 110.456], description: "A companion peak to Zhangjiajie with a famous natural arch and glass walkways.", bestTime: "Apr–Oct", highlights: ["Tianmen Cave", "Coiling Dragon Cliff", "Skywalk"], emoji: "🌉" },
  { id: 97, name: "Zhangjiajie Grand Canyon", chineseName: "张家界大峡谷", province: "Hunan", coords: [29.472, 110.314], description: "A breathtaking gorge featuring the world's longest and highest glass-bottomed bridge.", bestTime: "Apr–Nov", highlights: ["Glass Bridge", "Canyon zipline", "Waterfall"], emoji: "🌉" },
  { id: 98, name: "Fanjing Mountain", chineseName: "梵净山", province: "Guizhou", coords: [27.900, 108.683], description: "A UNESCO World Heritage site, a sacred Buddhist mountain rising dramatically from the Wuling range.", bestTime: "Apr–Oct", highlights: ["Red Clouds Golden Summit", "New Golden Peak", "Ancient fir forest"], emoji: "🏔️" },
  { id: 99, name: "Libo Karst", chineseName: "荔波茂兰", province: "Guizhou", coords: [25.410, 107.874], description: "A UNESCO World Heritage site showcasing the world's most intact subtropical karst forest ecosystem.", bestTime: "Apr–Oct", highlights: ["Zhangjiang River", "Small Seven-Hole Scenic Area", "Big Seven-Hole"], emoji: "🌿" },
  { id: 100, name: "Xingwen Stone Sea", chineseName: "兴文石海", province: "Sichuan", coords: [28.303, 105.215], description: "A UNESCO Geopark with vast karst 'stone sea' formations and the world's largest collapse sinkhole.", bestTime: "Apr–Oct", highlights: ["Stone Sea", "Giant Panda Sinkhole", "Miao minority culture"], emoji: "🪨" },
];
